export const fakeStudentData = [
  {
    studentName: "Corette McVey",
    studentEmail: "cmcvey0@irs.gov",
    studentID: "27808-065",
    studentGrade: 1,
  },
  {
    studentName: "Aubert Sandell",
    studentEmail: "asandell1@netscape.com",
    studentID: "21695-117",
    studentGrade: 2,
  },
  {
    studentName: "Helga Hubberstey",
    studentEmail: "hhubberstey2@wikimedia.org",
    studentID: "61787-443",
    studentGrade: 3,
  },
  {
    studentName: "Gerta Beardsall",
    studentEmail: "gbeardsall3@stumbleupon.com",
    studentID: "66579-0014",
    studentGrade: 4,
  },
  {
    studentName: "Benito Stable",
    studentEmail: "bstable4@woothemes.com",
    studentID: "51393-7335",
    studentGrade: 5,
  },
  {
    studentName: "Elliott Gouldthorpe",
    studentEmail: "egouldthorpe5@cdc.gov",
    studentID: "43353-819",
    studentGrade: 6,
  },
  {
    studentName: "Celeste Marson",
    studentEmail: "cmarson6@engadget.com",
    studentID: "53499-2590",
    studentGrade: 7,
  },
  {
    studentName: "Benetta Yacob",
    studentEmail: "byacob7@aboutads.info",
    studentID: "0781-3166",
    studentGrade: 8,
  },
  {
    studentName: "Laetitia Gelly",
    studentEmail: "lgelly8@lycos.com",
    studentID: "58668-4111",
    studentGrade: 9,
  },
  {
    studentName: "Deanna MacEllen",
    studentEmail: "dmacellen9@jigsy.com",
    studentID: "58232-0528",
    studentGrade: 10,
  },
  {
    studentName: "Ulrica Youd",
    studentEmail: "uyouda@privacy.gov.au",
    studentID: "53807-518",
    studentGrade: 11,
  },
  {
    studentName: "Arney Mackison",
    studentEmail: "amackisonb@washingtonpost.com",
    studentID: "55289-895",
    studentGrade: 12,
  },
  {
    studentName: "Karlen MacKartan",
    studentEmail: "kmackartanc@marketwatch.com",
    studentID: "0597-0146",
    studentGrade: 13,
  },
  {
    studentName: "Louisa Dilke",
    studentEmail: "ldilked@businessinsider.com",
    studentID: "0703-4014",
    studentGrade: 14,
  },
  {
    studentName: "Gardy Le Floch",
    studentEmail: "glee@google.co.uk",
    studentID: "68382-354",
    studentGrade: 15,
  },
  {
    studentName: "Shelley Hains",
    studentEmail: "shainsf@economist.com",
    studentID: "54575-397",
    studentGrade: 16,
  },
  {
    studentName: "Bendite Monkman",
    studentEmail: "bmonkmang@twitpic.com",
    studentID: "24236-200",
    studentGrade: 17,
  },
  {
    studentName: "Carri Ferries",
    studentEmail: "cferriesh@webmd.com",
    studentID: "0054-8526",
    studentGrade: 18,
  },
  {
    studentName: "Karina McCurley",
    studentEmail: "kmccurleyi@vistaprint.com",
    studentID: "0378-0317",
    studentGrade: 19,
  },
  {
    studentName: "Camey McKenzie",
    studentEmail: "cmckenziej@1688.com",
    studentID: "57955-1531",
    studentGrade: 20,
  },
  {
    studentName: "Ursuline Stimson",
    studentEmail: "ustimsonk@amazon.co.uk",
    studentID: "55289-373",
    studentGrade: 21,
  },
  {
    studentName: "Tann Ellens",
    studentEmail: "tellensl@issuu.com",
    studentID: "55111-149",
    studentGrade: 22,
  },
  {
    studentName: "Virgie Broz",
    studentEmail: "vbrozm@quantcast.com",
    studentID: "13734-014",
    studentGrade: 23,
  },
  {
    studentName: "Becky Magnar",
    studentEmail: "bmagnarn@ebay.com",
    studentID: "59779-618",
    studentGrade: 24,
  },
  {
    studentName: "Deeyn Karolovsky",
    studentEmail: "dkarolovskyo@biglobe.ne.jp",
    studentID: "49349-927",
    studentGrade: 25,
  },
  {
    studentName: "Beniamino Corran",
    studentEmail: "bcorranp@jiathis.com",
    studentID: "50436-3944",
    studentGrade: 26,
  },
  {
    studentName: "Quincey Carthy",
    studentEmail: "qcarthyq@boston.com",
    studentID: "61096-0031",
    studentGrade: 27,
  },
  {
    studentName: "Ellynn Rubrow",
    studentEmail: "erubrowr@meetup.com",
    studentID: "47593-114",
    studentGrade: 28,
  },
  {
    studentName: "Tiffany Gimblet",
    studentEmail: "tgimblets@webs.com",
    studentID: "55154-1379",
    studentGrade: 29,
  },
  {
    studentName: "Manolo Di Matteo",
    studentEmail: "mdit@simplemachines.org",
    studentID: "55315-550",
    studentGrade: 30,
  },
  {
    studentName: "Neddy Prozillo",
    studentEmail: "nprozillou@squarespace.com",
    studentID: "60512-6545",
    studentGrade: 31,
  },
  {
    studentName: "Dilan Haburne",
    studentEmail: "dhaburnev@howstuffworks.com",
    studentID: "0485-0051",
    studentGrade: 32,
  },
  {
    studentName: "Kelsey Paternoster",
    studentEmail: "kpaternosterw@pagesperso-orange.fr",
    studentID: "63323-120",
    studentGrade: 33,
  },
  {
    studentName: "Christie Leindecker",
    studentEmail: "cleindeckerx@simplemachines.org",
    studentID: "16590-265",
    studentGrade: 34,
  },
  {
    studentName: "Mel Ladell",
    studentEmail: "mladelly@phpbb.com",
    studentID: "63874-201",
    studentGrade: 35,
  },
  {
    studentName: "Eliot Giacaponi",
    studentEmail: "egiacaponiz@stanford.edu",
    studentID: "54868-5969",
    studentGrade: 36,
  },
  {
    studentName: "Annaliese Weitzel",
    studentEmail: "aweitzel10@webnode.com",
    studentID: "11673-230",
    studentGrade: 37,
  },
  {
    studentName: "Stanton Saipy",
    studentEmail: "ssaipy11@sina.com.cn",
    studentID: "60344-7001",
    studentGrade: 38,
  },
  {
    studentName: "Lilian Awin",
    studentEmail: "lawin12@ow.ly",
    studentID: "36987-2536",
    studentGrade: 39,
  },
  {
    studentName: "Adair Madgwich",
    studentEmail: "amadgwich13@prlog.org",
    studentID: "23155-063",
    studentGrade: 40,
  },
  {
    studentName: "Aldis Prendergrast",
    studentEmail: "aprendergrast14@dropbox.com",
    studentID: "69041-001",
    studentGrade: 41,
  },
  {
    studentName: "Ania Bodycomb",
    studentEmail: "abodycomb15@wikispaces.com",
    studentID: "13734-124",
    studentGrade: 42,
  },
  {
    studentName: "Tiff Janiak",
    studentEmail: "tjaniak16@blogger.com",
    studentID: "68084-201",
    studentGrade: 43,
  },
  {
    studentName: "Pall Adiscot",
    studentEmail: "padiscot17@imdb.com",
    studentID: "0363-0189",
    studentGrade: 44,
  },
  {
    studentName: "Georgie Brundrett",
    studentEmail: "gbrundrett18@nps.gov",
    studentID: "37000-204",
    studentGrade: 45,
  },
  {
    studentName: "Emmett Vasyatkin",
    studentEmail: "evasyatkin19@senate.gov",
    studentID: "49349-441",
    studentGrade: 46,
  },
  {
    studentName: "Irwin Kendall",
    studentEmail: "ikendall1a@toplist.cz",
    studentID: "37000-389",
    studentGrade: 47,
  },
  {
    studentName: "Dell Kobera",
    studentEmail: "dkobera1b@skyrock.com",
    studentID: "17238-910",
    studentGrade: 48,
  },
  {
    studentName: "Aldric Baselio",
    studentEmail: "abaselio1c@mysql.com",
    studentID: "49348-305",
    studentGrade: 49,
  },
  {
    studentName: "Gusty Oaks",
    studentEmail: "goaks1d@cargocollective.com",
    studentID: "41250-408",
    studentGrade: 50,
  },
  {
    studentName: "Ilsa Killwick",
    studentEmail: "ikillwick1e@zimbio.com",
    studentID: "21695-263",
    studentGrade: 51,
  },
  {
    studentName: "Annmarie Kuschke",
    studentEmail: "akuschke1f@weather.com",
    studentID: "55154-5686",
    studentGrade: 52,
  },
  {
    studentName: "Aurea Dumbare",
    studentEmail: "adumbare1g@scribd.com",
    studentID: "43353-344",
    studentGrade: 53,
  },
  {
    studentName: "Birgit Abramov",
    studentEmail: "babramov1h@g.co",
    studentID: "55910-234",
    studentGrade: 54,
  },
  {
    studentName: "Irene Finby",
    studentEmail: "ifinby1i@theglobeandmail.com",
    studentID: "0268-6760",
    studentGrade: 55,
  },
  {
    studentName: "Ward Ubank",
    studentEmail: "wubank1j@fema.gov",
    studentID: "55150-114",
    studentGrade: 56,
  },
  {
    studentName: "Alonso Prest",
    studentEmail: "aprest1k@infoseek.co.jp",
    studentID: "62750-059",
    studentGrade: 57,
  },
  {
    studentName: "Kasey Barbie",
    studentEmail: "kbarbie1l@yahoo.com",
    studentID: "16590-327",
    studentGrade: 58,
  },
  {
    studentName: "Lisette Alden",
    studentEmail: "lalden1m@blogtalkradio.com",
    studentID: "43538-192",
    studentGrade: 59,
  },
  {
    studentName: "Pattie Vinall",
    studentEmail: "pvinall1n@washingtonpost.com",
    studentID: "76237-258",
    studentGrade: 60,
  },
  {
    studentName: "Morganica Buckby",
    studentEmail: "mbuckby1o@jigsy.com",
    studentID: "43742-0090",
    studentGrade: 61,
  },
  {
    studentName: "Gretchen Glader",
    studentEmail: "gglader1p@ebay.co.uk",
    studentID: "19515-891",
    studentGrade: 62,
  },
  {
    studentName: "Fairleigh Rosbottom",
    studentEmail: "frosbottom1q@bloglovin.com",
    studentID: "49230-200",
    studentGrade: 63,
  },
  {
    studentName: "Zeb Risen",
    studentEmail: "zrisen1r@g.co",
    studentID: "49643-409",
    studentGrade: 64,
  },
  {
    studentName: "Michal Haquin",
    studentEmail: "mhaquin1s@trellian.com",
    studentID: "64205-928",
    studentGrade: 65,
  },
  {
    studentName: "Mavra Cowhig",
    studentEmail: "mcowhig1t@mtv.com",
    studentID: "55910-756",
    studentGrade: 66,
  },
  {
    studentName: "Charla Street",
    studentEmail: "cstreet1u@mysql.com",
    studentID: "48951-2075",
    studentGrade: 67,
  },
  {
    studentName: "Sibelle Sterzaker",
    studentEmail: "ssterzaker1v@w3.org",
    studentID: "54575-921",
    studentGrade: 68,
  },
  {
    studentName: "Roslyn Lembrick",
    studentEmail: "rlembrick1w@comsenz.com",
    studentID: "76282-258",
    studentGrade: 69,
  },
  {
    studentName: "Francesca O'Carran",
    studentEmail: "focarran1x@mayoclinic.com",
    studentID: "69020-209",
    studentGrade: 70,
  },
  {
    studentName: "Normie Oboy",
    studentEmail: "noboy1y@google.de",
    studentID: "0179-0070",
    studentGrade: 71,
  },
  {
    studentName: "Gerri Wordesworth",
    studentEmail: "gwordesworth1z@yellowbook.com",
    studentID: "63739-631",
    studentGrade: 72,
  },
  {
    studentName: "Lilas Thouless",
    studentEmail: "lthouless20@thetimes.co.uk",
    studentID: "0378-1803",
    studentGrade: 73,
  },
  {
    studentName: "Humphrey De Bischof",
    studentEmail: "hde21@oakley.com",
    studentID: "63187-130",
    studentGrade: 74,
  },
  {
    studentName: "Byram Colgan",
    studentEmail: "bcolgan22@jimdo.com",
    studentID: "49349-612",
    studentGrade: 75,
  },
  {
    studentName: "Bevon Verry",
    studentEmail: "bverry23@liveinternet.ru",
    studentID: "37000-798",
    studentGrade: 76,
  },
  {
    studentName: "Jean Bonnick",
    studentEmail: "jbonnick24@dropbox.com",
    studentID: "21695-515",
    studentGrade: 77,
  },
  {
    studentName: "Dosi Francke",
    studentEmail: "dfrancke25@surveymonkey.com",
    studentID: "36987-2056",
    studentGrade: 78,
  },
  {
    studentName: "Casey Charte",
    studentEmail: "ccharte26@apple.com",
    studentID: "21695-935",
    studentGrade: 79,
  },
  {
    studentName: "Blaire Pyrton",
    studentEmail: "bpyrton27@taobao.com",
    studentID: "13537-161",
    studentGrade: 80,
  },
  {
    studentName: "Sullivan Roderick",
    studentEmail: "sroderick28@theguardian.com",
    studentID: "0944-4351",
    studentGrade: 81,
  },
  {
    studentName: "Kassie Mayer",
    studentEmail: "kmayer29@msn.com",
    studentID: "54111-205",
    studentGrade: 82,
  },
  {
    studentName: "Barth Hollindale",
    studentEmail: "bhollindale2a@intel.com",
    studentID: "21695-108",
    studentGrade: 83,
  },
  {
    studentName: "Nadya Itzcak",
    studentEmail: "nitzcak2b@mozilla.com",
    studentID: "0555-9025",
    studentGrade: 84,
  },
  {
    studentName: "Karney Tennewell",
    studentEmail: "ktennewell2c@msu.edu",
    studentID: "60429-076",
    studentGrade: 85,
  },
  {
    studentName: "Maiga McCarver",
    studentEmail: "mmccarver2d@scribd.com",
    studentID: "17772-103",
    studentGrade: 86,
  },
  {
    studentName: "Libbi Matzl",
    studentEmail: "lmatzl2e@auda.org.au",
    studentID: "48951-3091",
    studentGrade: 87,
  },
  {
    studentName: "Xylia Itskovitz",
    studentEmail: "xitskovitz2f@cornell.edu",
    studentID: "0591-3592",
    studentGrade: 88,
  },
  {
    studentName: "Stevena Ashman",
    studentEmail: "sashman2g@phoca.cz",
    studentID: "55910-245",
    studentGrade: 89,
  },
  {
    studentName: "Yuri Kellitt",
    studentEmail: "ykellitt2h@economist.com",
    studentID: "62011-0233",
    studentGrade: 90,
  },
  {
    studentName: "Kym Hastin",
    studentEmail: "khastin2i@bizjournals.com",
    studentID: "0904-6100",
    studentGrade: 91,
  },
  {
    studentName: "Riobard Hartness",
    studentEmail: "rhartness2j@theglobeandmail.com",
    studentID: "52125-605",
    studentGrade: 92,
  },
  {
    studentName: "Isacco Swafield",
    studentEmail: "iswafield2k@geocities.com",
    studentID: "0517-0020",
    studentGrade: 93,
  },
  {
    studentName: "Clementine Cowin",
    studentEmail: "ccowin2l@geocities.jp",
    studentID: "52686-226",
    studentGrade: 94,
  },
  {
    studentName: "Darbie Jewess",
    studentEmail: "djewess2m@theglobeandmail.com",
    studentID: "10056-704",
    studentGrade: 95,
  },
  {
    studentName: "Domeniga Junifer",
    studentEmail: "djunifer2n@icq.com",
    studentID: "66975-406",
    studentGrade: 96,
  },
  {
    studentName: "Celie Bumfrey",
    studentEmail: "cbumfrey2o@europa.eu",
    studentID: "17271-116",
    studentGrade: 97,
  },
  {
    studentName: "Eugenie Bleddon",
    studentEmail: "ebleddon2p@hostgator.com",
    studentID: "50458-595",
    studentGrade: 98,
  },
  {
    studentName: "Shaina Gocke",
    studentEmail: "sgocke2q@gmpg.org",
    studentID: "65197-212",
    studentGrade: 99,
  },
  {
    studentName: "Orland Fydoe",
    studentEmail: "ofydoe2r@nsw.gov.au",
    studentID: "63739-538",
    studentGrade: 100,
  },
];
